import { config } from "dotenv";

config();

const {
  PORT,
  MONGO_URI,
  REDIS_URI,
  ACTIVATION_SECRET,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  SMTP_HOST,
  SMTP_PORT,
  SMTP_SERVICE,
  SMTP_USER,
  SMTP_PASS,
  GEMINI_API,
  BASIC_PLAN_ACCESS_TOKEN,
  ADVANCE_PLAN_ACCESS_TOKEN
} = process.env;

export const _config = {
  PORT,
  MONGO_URI,
  REDIS_URI,
  ACTIVATION_SECRET,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  SMTP_HOST,
  SMTP_PORT,
  SMTP_SERVICE,
  SMTP_USER,
  SMTP_PASS,
  GEMINI_API,
  BASIC_PLAN_ACCESS_TOKEN,
  ADVANCE_PLAN_ACCESS_TOKEN
};
